refinery29/sitemap

CONTRIBUTING.md
Makefile

Enhancement: Make it target first target

---

README.md

Fix: Code Climate badges

---

.travis.yml

Fix: Shift Travis environment variables

---

src/Component/Video/Video.php
test/Component/Image/ImageTest.php
test/Component/News/NewsTest.php
test/Component/News/PublicationTest.php
test/Component/SitemapIndexTest.php
test/Component/SitemapTest.php
test/Component/UrlSetTest.php
test/Component/UrlTest.php
test/Component/Video/GalleryLocationTest.php
test/Component/Video/PlatformTest.php
test/Component/Video/PlayerLocationTest.php
test/Component/Video/PriceTest.php
test/Component/Video/RestrictionTest.php
test/Component/Video/TagTest.php
test/Component/Video/UploaderTest.php
test/Component/Video/VideoTest.php

Fix: Assert that classes are final

---

README.md

Fix video example readme typo

---

composer.json
composer.lock

Fix: Add @alucic as author

---

test/Writer/Image/ImageWriterTest.php

Fix: Namespace

---

.travis.yml
Makefile
test/Integration/phpunit.xml

Enhancement: Prepare for running integration tests

---

test/Integration/Writer/SitemapIndexWriterTest.php
test/Integration/Writer/UrlSetWriterTest.php

Fix: Add integration tests

---

test/Unit/Writer/AbstractTestCase.php

Fix: Remove useless docblocks

---

src/Component/Image/Image.php
test/Integration/Writer/UrlSetWriterTest.php
test/Unit/Component/Image/ImageTest.php

Fix: Turn Image into immutable object

---

.github/PULL_REQUEST_TEMPLATE.md

Fix: Remove extra spaces from PULL_REQUEST_TEMPLATE.md

---

README.md

Fix: Update examples in README.md

---

src/Component/Video/Price.php
test/Unit/Component/Video/PriceTest.php

Fix: Turn Price into an immutable object

---

src/Component/Video/Video.php
test/Unit/Component/Video/VideoTest.php

Fix: Turn Video into immutable object

---

src/Component/Video/Restriction.php

Fix: Add missing import

---

test/Integration/Writer/SitemapIndexWriterTest.php
test/Integration/Writer/UrlSetWriterTest.php

Fix: Provide thorough examples in tests

---

composer.json
composer.lock

This PR
💁 For reference, see https://github.com/refinery29/php-cs-fixer-config/compare/0.4.4...0.4.11.

Fix: Update fabpot/php-cs-fixer

---

src/Component/Video/VideoInterface.php

Fix: Comment

---

test/Unit/Component/Video/PriceTest.php
test/Unit/Writer/UrlWriterTest.php
test/Unit/Writer/Video/PriceWriterTest.php
test/Unit/Writer/Video/VideoWriterTest.php

Fix: Wrapping

---

test/Unit/Component/UrlTest.php

Fix: Remove unused import

---

.travis.yml
composer.json
composer.lock

Fix: Drop PHP 5.5

---

composer.json
composer.lock
test/Integration/phpunit.xml
test/Unit/phpunit.xml

This PR
💁‍♂️ For reference, see https://github.com/sebastianbergmann/phpunit/compare/4.8.27...5.6.5.

Enhancement: Update phpunit/phpunit

---

test/Unit/Component/Image/ImageTest.php
test/Unit/Component/News/NewsTest.php
test/Unit/Component/News/PublicationTest.php
test/Unit/Component/SitemapIndexTest.php
test/Unit/Component/SitemapTest.php
test/Unit/Component/UrlSetTest.php
test/Unit/Component/UrlTest.php
test/Unit/Component/Video/GalleryLocationTest.php
test/Unit/Component/Video/PlatformTest.php
test/Unit/Component/Video/PlayerLocationTest.php
test/Unit/Component/Video/PriceTest.php
test/Unit/Component/Video/RestrictionTest.php
test/Unit/Component/Video/TagTest.php
test/Unit/Component/Video/UploaderTest.php
test/Unit/Component/Video/VideoTest.php

Fix: Use assertFinal()
