refinery29/sitemap

- README.md
> Fix: No need to reference repository

- CONDUCT.md
- README.md
This PR
:information_desk_person: This is the code of conduct we've adopted for [`refinery29/piston`](https://github.com/refinery29/piston/blob/master/.github/CONDUCT.md), too.
> Fix: Add missing code of conduct

- test/Component/News/NewsTest.php
- test/Component/Video/RestrictionTest.php
- test/Component/Video/VideoTest.php
- test/Writer/News/NewsWriterTest.php
- test/Writer/UrlSetWriterTest.php
- test/Writer/UrlWriterTest.php
- test/Writer/Video/PlatformWriterTest.php
- test/Writer/Video/RestrictionWriterTest.php
- test/Writer/Video/VideoWriterTest.php
> Fix: Actually use constants defined in interfaces

- test/Component/SitemapIndexTest.php
> Fix: No need to disable constructor

- test/Writer/Video/VideoWriterTest.php
> Fix: Add arguments to docblock

- test/Component/Image/ImageTest.php
- test/Component/News/NewsTest.php
- test/Component/News/PublicationTest.php
- test/Component/SitemapTest.php
- test/Component/Video/GalleryLocationTest.php
- test/Component/Video/PlatformTest.php
- test/Component/Video/PlayerLocationTest.php
- test/Component/Video/PriceTest.php
- test/Component/Video/RestrictionTest.php
- test/Component/Video/TagTest.php
- test/Component/Video/UploaderTest.php
- test/Component/Video/VideoTest.php
> Fix: Use more specific names for tests

- test/Component/Image/ImageTest.php
- test/Component/News/NewsTest.php
- test/Component/News/PublicationTest.php
- test/Component/SitemapTest.php
- test/Component/Video/GalleryLocationTest.php
- test/Component/Video/PlatformTest.php
- test/Component/Video/PlayerLocationTest.php
- test/Component/Video/PriceTest.php
- test/Component/Video/RestrictionTest.php
- test/Component/Video/TagTest.php
- test/Component/Video/UploaderTest.php
- test/Component/Video/VideoTest.php
> Fix: Use reflection to assert that interfaces are implemented

- src/Component/SitemapIndex.php
- src/Component/Url.php
- src/Component/Video/Platform.php
- src/Component/Video/Video.php
- test/Component/SitemapIndexTest.php
- test/Component/UrlTest.php
- test/Component/Video/PlatformTest.php
- test/Component/Video/VideoTest.php
> Fix: Throw InvalidArgumentException

- composer.json
- composer.lock
- src/Component/News/News.php
- src/Component/Url.php
- src/Component/Video/Platform.php
- src/Component/Video/PlayerLocation.php
- src/Component/Video/Price.php
- src/Component/Video/Restriction.php
- src/Component/Video/Video.php
> Enhancement: Use beberlei/assert to guard against invalid values

- src/Component/News/News.php
- src/Component/Video/Platform.php
- src/Component/Video/PlayerLocation.php
- src/Component/Video/Price.php
- src/Component/Video/Restriction.php
- src/Component/Video/Video.php
> Fix: Rename variable containing choices

- src/Component/UrlSetInterface.php
- test/Component/UrlSetInterfaceTest.php
This PR
:information_desk_person: For reference, see https://support.google.com/webmasters/answer/183668?hl=en:
> All formats limit a single sitemap to 10MB (uncompressed) and 50,000 URLs. If you have a larger file or more URLs, you will have to break your list into multiple sitemaps. You can optionally create a sitemap index file (a file that points to a list of sitemaps) and submit that single index file to Google. You can submit multiple sitemaps and/or sitemap index files to Google.
> Enhancement: Add constant for maximum number of URLs

- README.md
- src/Component/UrlSet.php
- test/Component/UrlSetTest.php
> Fix: Prevent adding more than 50,000 URLs to a UrlSet

- src/Component/News/News.php
- src/Component/News/NewsInterface.php
- src/Component/Sitemap.php
- src/Component/SitemapInterface.php
- src/Component/Url.php
- src/Component/UrlInterface.php
- src/Component/Video/Video.php
- src/Component/Video/VideoInterface.php
- src/Writer/News/NewsWriter.php
- src/Writer/SitemapWriter.php
- src/Writer/UrlWriter.php
- src/Writer/Video/VideoWriter.php
This PR
:information_desk_person: Since we require PHP5.5, this is safe (and nice).
> Fix: Use DateTimeInterface instead of DateTime

- .gitattributes
> Fix: Do not export .github directory

- src/Component/Url.php
- src/Component/Video/Video.php
- src/Writer/Image/ImageWriter.php
- src/Writer/News/NewsWriter.php
- src/Writer/News/PublicationWriter.php
- src/Writer/SitemapIndexWriter.php
- src/Writer/SitemapWriter.php
- src/Writer/UrlSetWriter.php
- src/Writer/UrlWriter.php
- src/Writer/Video/GalleryLocationWriter.php
- src/Writer/Video/PlatformWriter.php
- src/Writer/Video/PlayerLocationWriter.php
- src/Writer/Video/PriceWriter.php
- src/Writer/Video/RestrictionWriter.php
- src/Writer/Video/TagWriter.php
- src/Writer/Video/UploaderWriter.php
- src/Writer/Video/VideoWriter.php
This PR
:information_desk_person: Having these docblocks has no benefits, only costs.
> Fix: Remove useless docblocks

- src/Writer/Image/ImageWriter.php
- src/Writer/News/NewsWriter.php
- src/Writer/News/PublicationWriter.php
- src/Writer/SitemapIndexWriter.php
- src/Writer/SitemapWriter.php
- src/Writer/UrlSetWriter.php
- src/Writer/UrlWriter.php
- src/Writer/Video/GalleryLocationWriter.php
- src/Writer/Video/PlatformWriter.php
- src/Writer/Video/PlayerLocationWriter.php
- src/Writer/Video/PriceWriter.php
- src/Writer/Video/RestrictionWriter.php
- src/Writer/Video/TagWriter.php
- src/Writer/Video/UploaderWriter.php
- src/Writer/Video/VideoWriter.php
- test/Writer/Image/ImageWriterTest.php
- test/Writer/News/NewsWriterTest.php
- test/Writer/News/PublicationWriterTest.php
- test/Writer/SitemapIndexWriterTest.php
- test/Writer/SitemapWriterTest.php
- test/Writer/UrlSetWriterTest.php
- test/Writer/UrlWriterTest.php
- test/Writer/Video/GalleryLocationWriterTest.php
- test/Writer/Video/PlatformWriterTest.php
- test/Writer/Video/PlayerLocationWriterTest.php
- test/Writer/Video/PriceWriterTest.php
- test/Writer/Video/RestrictionWriterTest.php
- test/Writer/Video/TagWriterTest.php
- test/Writer/Video/UploaderWriterTest.php
- test/Writer/Video/VideoWriterTest.php
This PR
:information_desk_person: The problem is this
* the documentation is currently wrong
* for the outmost writers, the `XmlWriter` needs to be made an optional argument
* consistency wins (inner writers should also have flipped arguments)
> Fix: Flip arguments

- README.md
> Fix: Monospace the filename

- src/Writer/SitemapWriter.php
- src/Writer/UrlWriter.php
- src/Writer/Video/GalleryLocationWriter.php
- src/Writer/Video/PlatformWriter.php
- src/Writer/Video/PlayerLocationWriter.php
- src/Writer/Video/PriceWriter.php
- src/Writer/Video/RestrictionWriter.php
- src/Writer/Video/TagWriter.php
- src/Writer/Video/UploaderWriter.php
- src/Writer/Video/VideoWriter.php
This PR
:information_desk_person: The idea is this, while it's of course possible to create components and just use one of the corresponding writers marked as internal here, as someone consuming the package you're mostly interested in either generating 
* a `Component\SitemapIndex` and then using a `Writer\SitemapIndexWriter`, see https://support.google.com/webmasters/answer/75712?rd=1:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<sitemap>
<loc>http://www.example.com/sitemap1.xml.gz</loc>
<lastmod>2004-10-01T18:23:17+00:00</lastmod>
</sitemap>
<sitemap>
<loc>http://www.example.com/sitemap2.xml.gz</loc>
<lastmod>2005-01-01</lastmod>
</sitemap>
</sitemapindex>
```
* a `Component\UrlSet` and then using a …
> Fix: Mark internal writers as internal

- src/Writer/SitemapIndexWriter.php
- src/Writer/UrlSetWriter.php
- test/Writer/AbstractTestCase.php
- test/Writer/SitemapIndexWriterTest.php
- test/Writer/UrlSetWriterTest.php
> Fix: Actually start and end documents

- src/Writer/SitemapIndexWriter.php
- src/Writer/UrlSetWriter.php
- test/Writer/AbstractTestCase.php
- test/Writer/SitemapIndexWriterTest.php
- test/Writer/UrlSetWriterTest.php
This PR
Follows #44.
:information_desk_person: This is what we're most interested in, right?!
> Enhancement: Return generated XML from writers

- src/Writer/SitemapIndexWriter.php
- src/Writer/UrlSetWriter.php
- test/Unit/Writer/AbstractTestCase.php
- test/Unit/Writer/SitemapIndexWriterTest.php
- test/Unit/Writer/UrlSetWriterTest.php
> Fix: Open memory

- src/Writer/SitemapIndexWriter.php
- src/Writer/UrlSetWriter.php
- test/Integration/Writer/SitemapIndexWriterTest.php
- test/Integration/Writer/UrlSetWriterTest.php
> Fix: Make XMLWriter an optional argument

- src/Component/News/News.php
- test/Unit/Component/News/NewsTest.php
> Fix: Turn News into an immutable object

- src/Component/Video/GalleryLocation.php
- test/Unit/Component/Video/GalleryLocationTest.php
> Fix: Turn GalleryLocation into immutable object

- src/Component/Video/Platform.php
- test/Unit/Component/Video/PlatformTest.php
> Fix: Turn Platform into an immutable object

- src/Component/Video/PlayerLocation.php
- test/Integration/Writer/UrlSetWriterTest.php
- test/Unit/Component/Video/PlayerLocationTest.php
> Fix: Turn PlayerLocation into an immutable object

- src/Component/Video/Restriction.php
- test/Unit/Component/Video/RestrictionTest.php
> Fix: Turn Restriction into an immutable object

- src/Component/Video/Uploader.php
- test/Unit/Component/Video/UploaderTest.php
> Fix: Turn Uploader into immutable object

- src/Component/Sitemap.php
- test/Integration/Writer/SitemapIndexWriterTest.php
- test/Unit/Component/SitemapTest.php
> Fix: Turn Sitemap into an immutable object

- src/Component/SitemapIndex.php
- src/Component/SitemapIndexInterface.php
- test/Integration/Writer/SitemapIndexWriterTest.php
- test/Unit/Component/SitemapIndexTest.php
> Fix: Turn SitemapIndex into an immutable object

- README.md
- src/Component/Url.php
- test/Integration/Writer/UrlSetWriterTest.php
- test/Unit/Component/UrlTest.php
> Fix: Turn Url into an immutable object

- README.md
- src/Component/UrlSet.php
- src/Component/UrlSetInterface.php
- test/Integration/Writer/UrlSetWriterTest.php
- test/Unit/Component/UrlSetTest.php
> Fix: Turn UrlSet into an immutable object

- src/Component/Image/Image.php
- test/Unit/Component/Image/ImageTest.php
> Fix: Reject invalid location

- src/Component/Image/Image.php
- test/Unit/Component/Image/ImageTest.php
> Fix: Reject non-string values in Component\Image

- src/Component/News/News.php
> Fix: Drop default value from mutator

- src/Component/News/News.php
- test/Unit/Component/News/NewsTest.php
> Fix: Reject non-string values in Component\News

- test/Unit/Component/DataProvider.php
- test/Unit/Component/Image/ImageTest.php
- test/Unit/Component/News/NewsTest.php
> Fix: Extract DataProvider

- src/Component/News/Publication.php
- test/Unit/Component/News/PublicationTest.php
> Fix: Reject non-string values in Component\News\Publication

- test/Unit/Component/Image/ImageTest.php
- test/Unit/Component/News/NewsTest.php
- test/Unit/Component/News/PublicationTest.php
- test/Util/DataProvider/InvalidString.php
This PR
Related to https://github.com/refinery29/test-util/pull/21.
:information_desk_person: Moving it now makes it easier to change when the referenced PR has been merged and tagged.
> Fix: Move data provider

- src/Component/Video/GalleryLocation.php
- test/Unit/Component/Video/GalleryLocationTest.php
> Fix: Reject invalid location in Component\Video\GalleryLocation

- src/Component/Video/GalleryLocation.php
- test/Unit/Component/Video/GalleryLocationTest.php
> Fix: Reject invalid string in Component\Video\GalleryLocation

- src/Component/Video/PlayerLocation.php
- test/Unit/Component/Video/PlayerLocationTest.php
> Fix: Reject invalid location in Component\Video\PlayerLocation

- src/Component/News/News.php
- src/Component/SitemapIndex.php
- src/Component/Url.php
- src/Component/UrlSet.php
- src/Component/Video/Platform.php
- src/Component/Video/PlayerLocation.php
- src/Component/Video/Price.php
- src/Component/Video/Restriction.php
- src/Component/Video/Video.php
This PR
:information_desk_person: Most methods using assertions didn't have `@throws` annotations, this fixes it.
> Fix: Update docblocks

- src/Component/News/News.php
- src/Component/Video/PlayerLocation.php
- test/Unit/Component/News/NewsTest.php
- test/Unit/Component/Video/PlayerLocationTest.php
> Fix: Reject null values

- test/Unit/Component/Video/PlatformTest.php
- test/Unit/Component/Video/PriceTest.php
- test/Unit/Component/Video/RestrictionTest.php
> Fix: Assert that null values are rejected

- src/Component/Video/Restriction.php
- test/Unit/Component/Video/RestrictionTest.php
> Fix: Reject non-string country codes from Component\Video\Restriction

- src/Component/Video/Tag.php
- test/Unit/Component/Video/TagTest.php
> Fix: Reject non-string value from Component\Video\Tag

- src/Component/Video/Uploader.php
- test/Unit/Component/Video/UploaderTest.php
> Fix: Reject non-string values in Component\Video\Tag

- src/Component/Video/Tag.php
> Fix: Remove docblock

- src/Component/Sitemap.php
- test/Unit/Component/SitemapTest.php
> Fix: Reject invalid URLs in Component\Sitemap

- src/Component/SitemapIndex.php
- test/Unit/Component/SitemapIndexTest.php
This PR
:information_desk_person: Google doesn't say anything about that being invalid, so we shouldn't either. Of course it doesn't make sense to add the same location twice, but that should be obvious. This is consistent with `UrlSet`s, we don't care if the same location is added there, too.
> Fix: Do not worry about duplication locations

- src/Component/Url.php
This PR
Follows #70.
:person_with_pouting_face: Ha!
> Fix: Remove arguments

- src/Component/UrlInterface.php
- test/Unit/Component/UrlInterfaceTest.php
> Fix: Add constants for minimum and maximum priority

- src/Component/Url.php
- test/Unit/Component/UrlTest.php
> Fix: Reject invalid values from Component\Url

- test/Unit/Component/Video/VideoTest.php
> Fix: Update docblock

- src/Component/Url.php
- test/Unit/Component/UrlTest.php
> Fix: Reject priorities with precision greater than 1

- src/Writer/UrlWriter.php
- test/Integration/Writer/UrlSetWriterTest.php
- test/Unit/Writer/UrlWriterTest.php
> Fix: Format priority, not 2

- test/Integration/Writer/UrlSetWriterTest.php
> Fix: Outdent

- test/Unit/Component/Image/ImageTest.php
- test/Unit/Component/News/NewsTest.php
- test/Unit/Component/News/PublicationTest.php
- test/Unit/Component/SitemapTest.php
- test/Unit/Component/UrlTest.php
- test/Unit/Component/Video/GalleryLocationTest.php
- test/Unit/Component/Video/PlayerLocationTest.php
- test/Unit/Component/Video/RestrictionTest.php
- test/Unit/Component/Video/TagTest.php
- test/Unit/Component/Video/UploaderTest.php
This PR
🙎 Works without them, but it looks weird.
> Fix: Add parentheses to data provider reference

- src/Component/Image/Image.php
- src/Component/News/News.php
- src/Component/News/Publication.php
- src/Component/Video/GalleryLocation.php
- src/Component/Video/Restriction.php
- src/Component/Video/Tag.php
- src/Component/Video/Uploader.php
- test/Unit/Component/Image/ImageTest.php
- test/Unit/Component/News/NewsTest.php
- test/Unit/Component/News/PublicationTest.php
- test/Unit/Component/Video/GalleryLocationTest.php
- test/Unit/Component/Video/RestrictionTest.php
- test/Unit/Component/Video/TagTest.php
- test/Unit/Component/Video/UploaderTest.php
> Fix: Reject blank strings

- test/Unit/Component/SitemapTest.php
- test/Unit/Component/UrlTest.php
- test/Unit/Component/Video/GalleryLocationTest.php
- test/Unit/Component/Video/PlatformTest.php
- test/Unit/Component/Video/PriceTest.php
- test/Unit/Component/Video/RestrictionTest.php
- test/Unit/Component/Video/UploaderTest.php
- test/Unit/Component/Video/VideoTest.php
> Fix: Use consistent naming for test methods

- src/Component/Video/Video.php
- src/Component/Video/VideoInterface.php
- test/Unit/Component/Video/VideoInterfaceTest.php
- test/Unit/Component/Video/VideoTest.php
This PR
💁 Seems natural that it shouldn't be less than `0`, but a named constant is better than a magic number.
> Fix: Extract constant for minimum view count value

- src/Component/News/News.php
- test/Unit/Component/News/NewsTest.php
> Fix: Reject duplicate genres

- test/Unit/Component/Video/PriceTest.php
- test/Unit/Writer/Video/PriceWriterTest.php
> Fix: Use constant for minimum price

- src/Component/Video/Price.php
- test/Unit/Component/Video/PriceTest.php
> Fix: Reject non-float values

- src/Component/Video/VideoInterface.php
- test/Unit/Component/News/NewsTest.php
- test/Unit/Component/UrlSetTest.php
- test/Unit/Component/UrlTest.php
- test/Unit/Component/Video/PlatformTest.php
- test/Unit/Component/Video/PlayerLocationTest.php
- test/Unit/Component/Video/PriceTest.php
- test/Unit/Component/Video/RestrictionTest.php
- test/Unit/Component/Video/VideoTest.php
> Fix: Increase verbosity of tests

- test/Unit/Component/Video/PriceTest.php
This PR
Follows #116.
🙍 This was the result of resolving a merge conflict.
> Fix: Too many arguments in constructor

- test/Unit/Writer/UrlWriterTest.php
- test/Unit/Writer/Video/VideoWriterTest.php
> Fix: Avoid magic numbers

- composer.json
- composer.lock
- src/Component/UrlSetInterface.php
This PR
💁 For reference, see http://github.com/refinery29/php-cs-fixer-config/compare/0.4.15...0.4.16.
> Fix: Update refinery29/php-cs-fixer-config

- composer.json
- composer.lock
This PR
💁 For reference, see https://github.com/refinery29/test-util/compare/0.4.1...0.4.3.
> Fix: Remove fzaninotto/faker and update refinery29/test-util

- test/Unit/Component/News/NewsTest.php
- test/Unit/Component/SitemapIndexTest.php
- test/Unit/Component/UrlSetTest.php
- test/Unit/Component/UrlTest.php
- test/Unit/Component/Video/VideoTest.php
- test/Unit/Writer/Image/ImageWriterTest.php
- test/Unit/Writer/News/NewsWriterTest.php
- test/Unit/Writer/News/PublicationWriterTest.php
- test/Unit/Writer/SitemapIndexWriterTest.php
- test/Unit/Writer/SitemapWriterTest.php
- test/Unit/Writer/UrlSetWriterTest.php
- test/Unit/Writer/UrlWriterTest.php
- test/Unit/Writer/Video/GalleryLocationWriterTest.php
- test/Unit/Writer/Video/PlatformWriterTest.php
- test/Unit/Writer/Video/PlayerLocationWriterTest.php
- test/Unit/Writer/Video/PriceWriterTest.php
- test/Unit/Writer/Video/RestrictionWriterTest.php
- test/Unit/Writer/Video/TagWriterTest.php
- test/Unit/Writer/Video/UploaderWriterTest.php
- test/Unit/Writer/Video/VideoWriterTest.php
> Fix: Use getMock()

- README.md
> Bugfix: Fix documentation

- src/Component/Url.php
> Bugfix: Change the doc block to reflect the function

- .travis.yml
> Fix: Remove HHVM from build matrix

- composer.json
- composer.lock
- test/Unit/Component/Image/ImageTest.php
- test/Unit/Component/News/NewsInterfaceTest.php
- test/Unit/Component/News/NewsTest.php
- test/Unit/Component/News/PublicationTest.php
- test/Unit/Component/SitemapIndexTest.php
- test/Unit/Component/SitemapTest.php
- test/Unit/Component/UrlSetInterfaceTest.php
- test/Unit/Component/UrlSetTest.php
- test/Unit/Component/UrlTest.php
- test/Unit/Component/Video/GalleryLocationTest.php
- test/Unit/Component/Video/PlatformTest.php
- test/Unit/Component/Video/PlayerLocationTest.php
- test/Unit/Component/Video/PriceTest.php
- test/Unit/Component/Video/RestrictionInterfaceTest.php
- test/Unit/Component/Video/RestrictionTest.php
- test/Unit/Component/Video/TagTest.php
- test/Unit/Component/Video/UploaderTest.php
- test/Unit/Component/Video/VideoTest.php
- test/Unit/Writer/AbstractTestCase.php
- test/Unit/Writer/SitemapIndexWriterTest.php
This PR
💁‍♂️ For reference, see https://github.com/refinery29/test-util/compare/0.4.3...0.9.5.
> Enhancement: Update refinery29/test-util

- test/Unit/Component/News/NewsTest.php
- test/Unit/Component/SitemapIndexTest.php
- test/Unit/Component/UrlSetTest.php
- test/Unit/Component/UrlTest.php
- test/Unit/Component/Video/VideoTest.php
- test/Unit/Writer/Image/ImageWriterTest.php
- test/Unit/Writer/News/NewsWriterTest.php
- test/Unit/Writer/News/PublicationWriterTest.php
- test/Unit/Writer/SitemapIndexWriterTest.php
- test/Unit/Writer/SitemapWriterTest.php
- test/Unit/Writer/UrlSetWriterTest.php
- test/Unit/Writer/UrlWriterTest.php
- test/Unit/Writer/Video/GalleryLocationWriterTest.php
- test/Unit/Writer/Video/PlatformWriterTest.php
- test/Unit/Writer/Video/PlayerLocationWriterTest.php
- test/Unit/Writer/Video/PriceWriterTest.php
- test/Unit/Writer/Video/RestrictionWriterTest.php
- test/Unit/Writer/Video/TagWriterTest.php
- test/Unit/Writer/Video/UploaderWriterTest.php
- test/Unit/Writer/Video/VideoWriterTest.php
> Fix: Use createMock() instead of deprecated getMock()

- test/Unit/Writer/UrlSetWriterTest.php
- test/Unit/Writer/UrlWriterTest.php
> Fix: Use createMock() instead of getMockBuilder() where possible

- test/Unit/Component/Image/ImageTest.php
- test/Unit/Component/News/NewsTest.php
- test/Unit/Component/News/PublicationTest.php
- test/Unit/Component/SitemapIndexTest.php
- test/Unit/Component/SitemapTest.php
- test/Unit/Component/UrlSetTest.php
- test/Unit/Component/UrlTest.php
- test/Unit/Component/Video/GalleryLocationTest.php
- test/Unit/Component/Video/PlatformTest.php
- test/Unit/Component/Video/PlayerLocationTest.php
- test/Unit/Component/Video/PriceTest.php
- test/Unit/Component/Video/RestrictionTest.php
- test/Unit/Component/Video/TagTest.php
- test/Unit/Component/Video/UploaderTest.php
- test/Unit/Component/Video/VideoTest.php
> Fix: Use expectException() instead of deprecated setExpectedException()

- test/Unit/Component/Image/ImageTest.php
- test/Unit/Component/News/NewsTest.php
- test/Unit/Component/News/PublicationTest.php
- test/Unit/Component/SitemapTest.php
- test/Unit/Component/UrlTest.php
- test/Unit/Component/Video/GalleryLocationTest.php
- test/Unit/Component/Video/PlatformTest.php
- test/Unit/Component/Video/PlayerLocationTest.php
- test/Unit/Component/Video/PriceTest.php
- test/Unit/Component/Video/RestrictionTest.php
- test/Unit/Component/Video/TagTest.php
- test/Unit/Component/Video/UploaderTest.php
- test/Unit/Component/Video/VideoTest.php
This PR
💁‍♂️ Otherwise PhpStorm complains.
> Fix: Use FQCNs for data provider annotations

- test/Unit/Component/Image/ImageTest.php
- test/Unit/Component/News/NewsTest.php
- test/Unit/Component/News/PublicationTest.php
- test/Unit/Component/SitemapIndexTest.php
- test/Unit/Component/SitemapTest.php
- test/Unit/Component/UrlTest.php
- test/Unit/Component/Video/GalleryLocationTest.php
- test/Unit/Component/Video/PlatformTest.php
- test/Unit/Component/Video/PlayerLocationTest.php
- test/Unit/Component/Video/PriceTest.php
- test/Unit/Component/Video/RestrictionTest.php
- test/Unit/Component/Video/TagTest.php
- test/Unit/Component/Video/UploaderTest.php
- test/Unit/Component/Video/VideoTest.php
> Fix: Use assertImplements()

- test/Unit/Component/News/NewsTest.php
- test/Unit/Component/SitemapIndexTest.php
- test/Unit/Component/UrlTest.php
- test/Unit/Component/Video/PlatformTest.php
- test/Unit/Component/Video/PlayerLocationTest.php
- test/Unit/Component/Video/PriceTest.php
- test/Unit/Component/Video/RestrictionTest.php
- test/Unit/Component/Video/VideoTest.php
> Fix: Use provideData()

- src/Component/News/News.php
- src/Component/Url.php
- src/Component/UrlSet.php
- src/Component/Video/Platform.php
- src/Component/Video/Video.php
- src/Writer/News/NewsWriter.php
- src/Writer/UrlWriter.php
- src/Writer/Video/PlatformWriter.php
- src/Writer/Video/PriceWriter.php
- src/Writer/Video/RestrictionWriter.php
- src/Writer/Video/VideoWriter.php
- test/Unit/Component/UrlSetTest.php
- test/Unit/Component/Video/PlayerLocationTest.php
- test/Unit/Component/Video/VideoTest.php
- test/Unit/Writer/News/NewsWriterTest.php
- test/Unit/Writer/UrlWriterTest.php
- test/Unit/Writer/Video/PlatformWriterTest.php
- test/Unit/Writer/Video/PriceWriterTest.php
- test/Unit/Writer/Video/RestrictionWriterTest.php
- test/Unit/Writer/Video/VideoWriterTest.php
This PR
Follows https://github.com/refinery29/test-util/pull/126.
💁‍♂️ For reference, see 
* https://twitter.com/Ocramius/status/811504929357660160
* http://php.net/manual/en/language.namespaces.faq.php#language.namespaces.faq.shortname2
* http://veewee.github.io/blog/optimizing-php-performance-by-fq-function-calls/
>Function or constant names that do not contain a backslash like name can be resolved in 2 different ways.
>
>First, the current namespace name is prepended to _name_.
>
>Finally, if the constant or function _name_ does not exist in the current namespace, a global constant or function _name_ is used if it exists.
> Fix: Remove need to resolve global function in current namespace
